
version: '3.8'

services:
  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
    networks:
      - app-network
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:660999304559.dkr.ecr.us-east-1.amazonaws.com/three-tier-app-backend:latest
    ports:
      - "5000:5000"
    depends_on:
      - database
    env_file:
      - ./backend/.env
    user: "1000:1000"
    read_only: true
    restart: always
    networks:
      - app-network
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: 660999304559.dkr.ecr.us-east-1.amazonaws.com/three-tier-app-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    user: "1000:1000"
    read_only: true
    restart: always
    networks:
      - app-network
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge

